apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume
  labels:
    type: local
  namespace: s057048-k8s-dev-cert-project-production

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /root/work/volume/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume
  namespace: s057048-k8s-dev-cert-project-production
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: volume