apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "*/2 9-19 * * 1-5"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 10
      template:
        spec:
          containers:
          - name: cronjob
            image: debian:jessie
            args:
            - date
          restartPolicy: Never