version: "2.4"
services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: "redis:alpine"
    volumes:
      - type: volume
        source: mydata
        target: /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 1s
    mem_limit: 500m
    cpus: 0.5
  test:
    image: curlimages/curl:7.73.0
    command: /bin/sh -c "sleep 10 && curl -s http://web:5000/ -i -vvv"

volumes:
  mydata: